return {
    "ThePrimeagen/refactoring.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
    config = function()
      require("refactoring").setup({})

      -- load refactoring Telescope extension
      require("telescope").load_extension("refactoring")

      vim.keymap.set(
      	{"n", "x"},
      	"<leader>rr",
    	  function() require('telescope').extensions.refactoring.refactors() end,
        { desc = "Opens refactoring UI"}
      )

      vim.keymap.set(
    	"n",
    	"<leader>rp",
    	function() require('refactoring').debug.printf({below = false}) end,
      { desc = "insertion of print statement to mark the calling of a function "}
      )


      vim.keymap.set({"x", "n"}, "<leader>rv", function() require('refactoring').debug.print_var() end, { desc = "insertion of print statement to print a variable at a given point in the code" })

      vim.keymap.set("n", "<leader>rc", function() require('refactoring').debug.cleanup({}) end, { desc = "cleanup of all print statements generated by the plugin" })
    end,
}
